/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nkp.pspValidator.web.backend.planner;

import nkp.pspValidator.web.backend.utils.Config;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello from Planner.";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        Config.init();
        Scheduler scheduler = new Scheduler();
        System.out.println(scheduler.run());
    }
}
