/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nkp.pspValidator.web.backend.job_execution_service;

public class App {
    public String getGreeting() {
        return "Hello from Job-execution service.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
