/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nkp.pspValidator.web.backend.users_service;

import nkp.pspValidator.web.backend.user_service.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
