/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nkp.pspValidator.web.backend.upload_service;

public class App {
    public String getGreeting() {
        return "Hello from Upload service.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
