/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package npk.pspValidator.web.backend.validation_manager_service;

public class App {
    public String getGreeting() {
        return "Hello from Validation-manager service.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
